### ISSUE TITLE
hfe support

### ISSUE THREAD

**Issue by PeterBBCUser** [picosonic/bbc-fdc#18]
Is it possible to support hfe file types as that format is more useful than fsd, especial if you have a flashfloppy drive emulator and for any type of copy protected discs that you may want to copy with it, as fsd's are not supported by flashfloppy
Thanks,
Peter.

**Comment by picosonic** [comment]
I’m currently working on adding .SCP SuperCard Pro write support. But will certainly consider other formats if there is interest.

There may be existing tools to convert between .SCP and other raw formats.

**Comment by PeterBBCUser** [comment]
yes HxCFloppyEmulator will let you save it in other formats and it does support .SCP (and many other formats) which meant I will then be able to export it as .HFE with that tool.
Thanks.

**Comment by picosonic** [comment]
I'll close this issue for now, as it's already covered by issue #4
