### ISSUE TITLE
PCB redesign - Enhancement 

### ISSUE THREAD

**Issue by rataweb** [picosonic/bbc-fdc#30]
Hi,
I think that it will be a good idea to put the pcb over the Pi, as a hat.
Best regards,

**Comment by picosonic** [comment]
That's a good idea and one I've looked into before. But I just don't have the time right now to do it.

By all means, please go ahead and redesign the PCB for a hat form factor and send over the gerbers

Thanks

**Comment by rataweb** [comment]
Hi,
I'm using EasyEDA for my pcb designs, but I don't know why I can't open your .sch file (using Eagle v9.6.2 same issue, I can't open it).
Could you upload in another format (ie Kicad, Altium or EasyEDA)?
Thanks,
